### ISSUE TITLE
software license

### ISSUE THREAD

**Issue by wibeasley** [redcap-tools/nef-c-sharp#1]
Ask Chris Nefcy  about the repo's [license](https://github.com/redcap-tools/nef-c-sharp/blob/master/LICENSE)
- [x] If the current MIT licene is ok
- [x] who should own the copyright.  By default it became "redcap-tools".  Should it be something like "Chris Nefcy" or "University of Washington" instead?

**Comment by sburns** [comment]
You automatically added a license with GitHub? Makes sense that it would default to redcap-tools but that is not correct for this repo. I think copyright should default to the original developer and depending on their agreement with their employer, they might need to change it.

**Comment by wibeasley** [comment]
Good point, @sburns, I've [changed it](https://github.com/redcap-tools/nef-c-sharp/commit/f4446dc1c7998128564e3ed2214b9f8dfed26293) in response.

And this is typically how I initialize the repo with a license:
![image](https://cloud.githubusercontent.com/assets/1372890/10668863/ccb85234-78a3-11e5-9d88-bc2f32976589.png)

**Comment by wibeasley** [comment]
On Oct 23, Chris emailed that he and others were happy with the MIT license.
